### ISSUE TITLE
Backend - Log in on backend, implement JWT

### ISSUE THREAD

**Issue by Aryanboxout** [Dylanluo05/DADY-Academy#9]
### Backend database - @dtsivkovski 
- [x] Create user database
- [x] Create roles database
- [x] Connect login as requirement for APIs

### Implement JWT Tokens - @evmyclipz 
- [x] Implement backend functionality
- [x] Call something on the backend to give JWT token for login
- [x] Authenticate to allow use of APIs

### Other - @dtsivkovski, @evmyclipz 
- [x] Deploy all backend implementation so that frontend can implement it
- [x] Coordinate with frontend developers to integrate with frontend

![image](https://user-images.githubusercontent.com/89223402/216224514-41b1d73c-52d0-4efc-9e23-61f0e87a01da.png)

**Comment by dtsivkovski** [comment]
JWT login now works, need to implement the code correctly on login page but works on [Login test page](https://dylanluo05.github.io/DADY-Academy/security/testpagelogin) and can test it on [physics page](https://dylanluo05.github.io/DADY-Academy/physics/energy). Use "dan@mail" for testing
